# Generated by Django 5.2.1 on 2025-05-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enqueteur',
            fields=[
                ('login_enq', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Login Enquêteur')),
                ('nom_enqueteur', models.CharField(max_length=255, verbose_name="Nom de l'Enquêteur")),
            ],
            options={
                'verbose_name': 'Enquêteur',
                'verbose_name_plural': 'Enquêteurs',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code_dr', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code DR')),
                ('nom_region', models.CharField(max_length=100, verbose_name='Nom de la Région')),
            ],
            options={
                'verbose_name': 'Région (DR)',
                'verbose_name_plural': 'Régions (DR)',
            },
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id_superviseur', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Superviseur')),
            ],
            options={
                'verbose_name': 'Superviseur',
                'verbose_name_plural': 'Superviseurs',
            },
        ),
        migrations.CreateModel(
            name='Menage',
            fields=[
                ('idmng', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Ménage')),
                ('superviseur_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Superviseur (du CSV)')),
                ('hh_trimestre', models.CharField(blank=True, max_length=50, null=True, verbose_name='HH Trimestre')),
                ('cons_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code CONS')),
                ('num_men_csv', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro Ménage (CSV)')),
                ('nom_cc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Chef de Canton/Commune')),
                ('nom_cm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Chef de Ménage')),
                ('statut_menage', models.IntegerField(choices=[(1, 'NON AFFECTE'), (2, 'AFFECTE'), (3, 'PARTIEL'), (4, 'COMPLET'), (7, "N'existe plus"), (8, 'Déménagé'), (9, 'Refus')], default=1, verbose_name='Statut du Ménage')),
                ('tirage', models.IntegerField(blank=True, null=True, verbose_name='Tirage (1 si attendu)')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=20, null=True)),
                ('taille_men', models.IntegerField(blank=True, null=True, verbose_name='Taille du Ménage')),
                ('nbr_eligible', models.IntegerField(blank=True, null=True, verbose_name='Nombre de Membres Éligibles')),
                ('date_enquete', models.DateField(blank=True, null=True, verbose_name="Date de l'enquête")),
                ('heure_debut_enquete', models.TimeField(blank=True, null=True, verbose_name='Heure début enquête')),
                ('heure_fin_enquete', models.TimeField(blank=True, null=True, verbose_name='Heure fin enquête')),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_rural', models.BooleanField(default=False, verbose_name='Milieu Rural')),
                ('enqueteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menages_collectes', to='api.enqueteur', verbose_name='Enquêteur')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menages', to='api.region', verbose_name='Région (DR)')),
            ],
            options={
                'verbose_name': 'Ménage',
                'verbose_name_plural': 'Ménages',
            },
        ),
        migrations.AddField(
            model_name='enqueteur',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enqueteurs', to='api.superviseur'),
        ),
    ]
